apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs
    server: 192.168.122.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: tasks-pvc
spec: 
  accessModes:
  -  ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels: 
        app: rails-app
    spec:
      containers: 
      - name: rails-app
        image: registry.lab/rails-app
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/var/db"
          name: tasks-vol
      volumes:
      - name: tasks-vol
        persistentVolumeClaim:
          claimName: tasks-pvc

---
apiVersion: v1
kind: Service
metadata: 
  name: rails-app-service
spec: 
  type: NodePort
  ports: 
  - port: 3000
    name: http
    appProtocol: http
  selector: 
    app: rails-app
